// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/calibracion": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Crea un nuevo registro de calibración para un sensor",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Calibración"
                ],
                "summary": "Crear una nueva calibración",
                "parameters": [
                    {
                        "description": "Datos de la calibración",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entities.CreateCalibracionRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/entities.CalibracionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/entities.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "No autorizado",
                        "schema": {
                            "$ref": "#/definitions/entities.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/entities.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/calibracion/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Obtiene los detalles de una calibración por su ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Calibración"
                ],
                "summary": "Obtener una calibración",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la calibración",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entities.CalibracionResponse"
                        }
                    },
                    "401": {
                        "description": "No autorizado",
                        "schema": {
                            "$ref": "#/definitions/entities.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/entities.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/entities.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Actualiza los datos de una calibración existente",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Calibración"
                ],
                "summary": "Actualizar una calibración",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la calibración",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Datos de actualización",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entities.UpdateCalibracionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entities.CalibracionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/entities.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/entities.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/entities.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Elimina una calibración por su ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Calibración"
                ],
                "summary": "Eliminar una calibración",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la calibración",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/entities.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/entities.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/colmena": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Obtiene la lista de todas las colmenas registradas",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Colmena"
                ],
                "summary": "Obtener todas las colmenas",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entities.ColmenasListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/entities.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Crea un nuevo registro de colmena",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Colmena"
                ],
                "summary": "Crear una nueva colmena",
                "parameters": [
                    {
                        "description": "Datos de la colmena",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entities.CreateColmenaRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/entities.ColmenaResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/entities.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/entities.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/colmena-raspberry": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Crea una nueva relación entre una colmena y un dispositivo Raspberry Pi",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Colmena-Raspberry"
                ],
                "summary": "Crear una nueva relación colmena-raspberry",
                "parameters": [
                    {
                        "description": "Datos de la relación",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entities.CreateColmenaRaspberryRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/entities.ColmenaRaspberryResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/entities.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/entities.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/colmena-raspberry/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Obtiene los detalles de una relación colmena-raspberry por su ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Colmena-Raspberry"
                ],
                "summary": "Obtener relación colmena-raspberry por ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la relación",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entities.ColmenaRaspberryResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/entities.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/entities.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Actualiza una relación existente entre colmena y Raspberry Pi",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Colmena-Raspberry"
                ],
                "summary": "Actualizar una relación colmena-raspberry",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la relación",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Datos de actualización",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entities.UpdateColmenaRaspberryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entities.ColmenaRaspberryResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/entities.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/entities.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/entities.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Elimina una relación existente entre colmena y Raspberry Pi",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Colmena-Raspberry"
                ],
                "summary": "Eliminar una relación colmena-raspberry",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la relación",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/entities.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/entities.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/colmena/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Obtiene los detalles de una colmena por su ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Colmena"
                ],
                "summary": "Obtener una colmena",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la colmena",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entities.ColmenaResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/entities.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/entities.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Actualiza los datos de una colmena existente",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Colmena"
                ],
                "summary": "Actualizar una colmena",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la colmena",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Datos de actualización",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entities.UpdateColmenaRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entities.ColmenaResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/entities.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/entities.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/entities.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Elimina una colmena por su ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Colmena"
                ],
                "summary": "Eliminar una colmena",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la colmena",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/entities.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/entities.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/colmena/{id}/estado": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Actualiza el estado de una colmena existente",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Colmena"
                ],
                "summary": "Actualizar estado de colmena",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la colmena",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Nuevo estado",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entities.UpdateEstadoColmenaRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entities.ColmenaResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/entities.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/entities.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/entities.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "entities.CalibracionResponse": {
            "type": "object",
            "properties": {
                "factor_calibracion": {
                    "type": "number",
                    "example": 1.5
                },
                "fecha_calibracion": {
                    "type": "string",
                    "example": "2024-03-20T10:00:00Z"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "id_colmena": {
                    "type": "integer",
                    "example": 1
                },
                "id_sensor": {
                    "type": "integer",
                    "example": 1
                },
                "offset_calibracion": {
                    "type": "number",
                    "example": 0.5
                },
                "valor_maximo": {
                    "type": "number",
                    "example": 30.5
                },
                "valor_minimo": {
                    "type": "number",
                    "example": 20.5
                }
            }
        },
        "entities.ColmenaRaspberryResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2024-03-20T10:00:00Z"
                },
                "estado": {
                    "type": "string",
                    "example": "activo"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "id_colmena": {
                    "type": "integer",
                    "example": 1
                },
                "id_raspberry": {
                    "type": "integer",
                    "example": 1
                },
                "updated_at": {
                    "type": "string",
                    "example": "2024-03-20T10:00:00Z"
                }
            }
        },
        "entities.ColmenaResponse": {
            "type": "object",
            "properties": {
                "area_ubicacion": {
                    "type": "string",
                    "example": "Sector Norte"
                },
                "estado": {
                    "type": "string",
                    "example": "activo"
                },
                "fecha_actualizacion": {
                    "type": "string",
                    "example": "2024-03-20 10:00:00"
                },
                "fecha_registro": {
                    "type": "string",
                    "example": "2024-03-20 10:00:00"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "identificador": {
                    "type": "string",
                    "example": "COL-001"
                },
                "nombre": {
                    "type": "string",
                    "example": "Colmena Principal"
                },
                "tipo_colmena": {
                    "type": "string",
                    "example": "Langstroth"
                }
            }
        },
        "entities.ColmenasListResponse": {
            "type": "object",
            "properties": {
                "colmenas": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entities.ColmenaResponse"
                    }
                }
            }
        },
        "entities.CreateCalibracionRequest": {
            "type": "object",
            "properties": {
                "factor_calibracion": {
                    "type": "number",
                    "example": 1.5
                },
                "fecha_calibracion": {
                    "type": "string",
                    "example": "2024-03-20T10:00:00Z"
                },
                "id_colmena": {
                    "type": "integer",
                    "example": 1
                },
                "id_sensor": {
                    "type": "integer",
                    "example": 1
                },
                "offset_calibracion": {
                    "type": "number",
                    "example": 0.5
                },
                "valor_maximo": {
                    "type": "number",
                    "example": 30.5
                },
                "valor_minimo": {
                    "type": "number",
                    "example": 20.5
                }
            }
        },
        "entities.CreateColmenaRaspberryRequest": {
            "type": "object",
            "required": [
                "estado"
            ],
            "properties": {
                "estado": {
                    "type": "string",
                    "enum": [
                        "activo",
                        "inactivo"
                    ],
                    "example": "activo"
                },
                "id_colmena": {
                    "type": "integer",
                    "example": 1
                },
                "id_raspberry": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "entities.CreateColmenaRequest": {
            "type": "object",
            "properties": {
                "area_ubicacion": {
                    "type": "string",
                    "example": "Sector Norte"
                },
                "estado": {
                    "type": "string",
                    "example": "activo"
                },
                "identificador": {
                    "type": "string",
                    "example": "COL-001"
                },
                "nombre": {
                    "type": "string",
                    "example": "Colmena Principal"
                },
                "tipo_colmena": {
                    "type": "string",
                    "example": "Langstroth"
                }
            }
        },
        "entities.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "description": "Mensaje de error",
                    "type": "string",
                    "example": "Credenciales inválidas. Por favor, verifique su usuario y contraseña"
                }
            }
        },
        "entities.UpdateCalibracionRequest": {
            "type": "object",
            "properties": {
                "factor_calibracion": {
                    "type": "number",
                    "example": 1.5
                },
                "fecha_calibracion": {
                    "type": "string",
                    "example": "2024-03-20T10:00:00Z"
                },
                "id_colmena": {
                    "type": "integer",
                    "example": 1
                },
                "id_sensor": {
                    "type": "integer",
                    "example": 1
                },
                "offset_calibracion": {
                    "type": "number",
                    "example": 0.5
                },
                "valor_maximo": {
                    "type": "number",
                    "example": 30.5
                },
                "valor_minimo": {
                    "type": "number",
                    "example": 20.5
                }
            }
        },
        "entities.UpdateColmenaRaspberryRequest": {
            "type": "object",
            "required": [
                "estado"
            ],
            "properties": {
                "estado": {
                    "type": "string",
                    "enum": [
                        "activo",
                        "inactivo"
                    ],
                    "example": "activo"
                },
                "id_colmena": {
                    "type": "integer",
                    "example": 1
                },
                "id_raspberry": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "entities.UpdateColmenaRequest": {
            "type": "object",
            "properties": {
                "area_ubicacion": {
                    "type": "string",
                    "example": "Sector Norte"
                },
                "estado": {
                    "type": "string",
                    "example": "activo"
                },
                "identificador": {
                    "type": "string",
                    "example": "COL-001"
                },
                "nombre": {
                    "type": "string",
                    "example": "Colmena Principal"
                },
                "tipo_colmena": {
                    "type": "string",
                    "example": "Langstroth"
                }
            }
        },
        "entities.UpdateEstadoColmenaRequest": {
            "type": "object",
            "required": [
                "estado"
            ],
            "properties": {
                "estado": {
                    "type": "string",
                    "enum": [
                        "activo",
                        "inactivo"
                    ],
                    "example": "inactivo"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "description": "Introduce el token Bearer. Ejemplo: \"Bearer {token}\"",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    },
    "externalDocs": {
        "description": "Autenticación API",
        "url": "http://localhost:8081/swagger/index.html"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{"http"},
	Title:            "API de Sensores para Colmenas",
	Description:      "API para la gestión de sensores en colmenas",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
