// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/calibracion": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Crea un nuevo registro de calibración para un sensor",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Calibración"
                ],
                "summary": "Crear una nueva calibración",
                "parameters": [
                    {
                        "description": "Datos de la calibración",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entities.CreateCalibracionRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/entities.CalibracionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/entities.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "No autorizado",
                        "schema": {
                            "$ref": "#/definitions/entities.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/entities.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/calibracion/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Obtiene los detalles de una calibración por su ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Calibración"
                ],
                "summary": "Obtener una calibración",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la calibración",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entities.CalibracionResponse"
                        }
                    },
                    "401": {
                        "description": "No autorizado",
                        "schema": {
                            "$ref": "#/definitions/entities.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/entities.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/entities.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Actualiza los datos de una calibración existente",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Calibración"
                ],
                "summary": "Actualizar una calibración",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la calibración",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Datos de actualización",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entities.UpdateCalibracionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entities.CalibracionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/entities.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/entities.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/entities.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Elimina una calibración por su ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Calibración"
                ],
                "summary": "Eliminar una calibración",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la calibración",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/entities.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/entities.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/colmena": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Obtiene la lista de todas las colmenas registradas",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Colmena"
                ],
                "summary": "Obtener todas las colmenas",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entities.ColmenasListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/entities.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Crea un nuevo registro de colmena",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Colmena"
                ],
                "summary": "Crear una nueva colmena",
                "parameters": [
                    {
                        "description": "Datos de la colmena",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entities.CreateColmenaRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/entities.ColmenaResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/entities.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/entities.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/colmena-raspberry": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Crea una nueva relación entre una colmena y un dispositivo Raspberry Pi",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Colmena-Raspberry"
                ],
                "summary": "Crear una nueva relación colmena-raspberry",
                "parameters": [
                    {
                        "description": "Datos de la relación",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entities.CreateColmenaRaspberryRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/entities.ColmenaRaspberryResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/entities.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/entities.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/colmena-raspberry/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Obtiene los detalles de una relación colmena-raspberry por su ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Colmena-Raspberry"
                ],
                "summary": "Obtener relación colmena-raspberry por ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la relación",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entities.ColmenaRaspberryResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/entities.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/entities.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Actualiza una relación existente entre colmena y Raspberry Pi",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Colmena-Raspberry"
                ],
                "summary": "Actualizar una relación colmena-raspberry",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la relación",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Datos de actualización",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entities.UpdateColmenaRaspberryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entities.ColmenaRaspberryResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/entities.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/entities.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/entities.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Elimina una relación existente entre colmena y Raspberry Pi",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Colmena-Raspberry"
                ],
                "summary": "Eliminar una relación colmena-raspberry",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la relación",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/entities.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/entities.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/colmena/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Obtiene los detalles de una colmena por su ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Colmena"
                ],
                "summary": "Obtener una colmena",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la colmena",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entities.ColmenaResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/entities.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/entities.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Actualiza los datos de una colmena existente",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Colmena"
                ],
                "summary": "Actualizar una colmena",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la colmena",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Datos de actualización",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entities.UpdateColmenaRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entities.ColmenaResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/entities.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/entities.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/entities.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Elimina una colmena por su ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Colmena"
                ],
                "summary": "Eliminar una colmena",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la colmena",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/entities.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/entities.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/colmena/{id}/estado": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Actualiza el estado de una colmena existente",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Colmena"
                ],
                "summary": "Actualizar estado de colmena",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la colmena",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Nuevo estado",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entities.UpdateEstadoColmenaRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entities.ColmenaResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/entities.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/entities.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/entities.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/raspberry": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Obtiene la lista de todos los dispositivos Raspberry Pi",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "RaspberryPi"
                ],
                "summary": "Obtener todos los Raspberry Pi",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entities.RaspberryPiListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/entities.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Registra un nuevo dispositivo Raspberry Pi en el sistema",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "RaspberryPi"
                ],
                "summary": "Crear un nuevo Raspberry Pi",
                "parameters": [
                    {
                        "description": "Datos del dispositivo",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entities.CreateRaspberryPiRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/entities.RaspberryPiResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/entities.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/entities.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/raspberry/mac/{mac}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Obtiene un dispositivo Raspberry Pi por su dirección MAC",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "RaspberryPi"
                ],
                "summary": "Obtener Raspberry Pi por MAC",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Dirección MAC del dispositivo",
                        "name": "mac",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entities.RaspberryPiResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/entities.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/entities.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/raspberry/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Obtiene los detalles de un dispositivo Raspberry Pi por su ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "RaspberryPi"
                ],
                "summary": "Obtener un Raspberry Pi",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del dispositivo",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entities.RaspberryPiResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/entities.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/entities.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Actualiza los datos de un dispositivo Raspberry Pi existente",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "RaspberryPi"
                ],
                "summary": "Actualizar un Raspberry Pi",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del dispositivo",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Datos de actualización",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entities.UpdateRaspberryPiRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entities.RaspberryPiResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/entities.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/entities.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/entities.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Elimina un dispositivo Raspberry Pi por su ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "RaspberryPi"
                ],
                "summary": "Eliminar un Raspberry Pi",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del dispositivo",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/entities.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/entities.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/raspberry/{id}/estado": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Actualiza el estado de un dispositivo Raspberry Pi",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "RaspberryPi"
                ],
                "summary": "Actualizar estado de Raspberry Pi",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del dispositivo",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Nuevo estado",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entities.UpdateEstadoRaspberryPiRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entities.RaspberryPiResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/entities.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/entities.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/entities.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/sensores": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Obtiene todos los sensores registrados",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Obtener todos los sensores",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entities.SensorResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Crea un nuevo sensor en la base de datos",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Crear un sensor",
                "parameters": [
                    {
                        "description": "Sensor a crear",
                        "name": "sensor",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entities.CreateSensorRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entities.SensorResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/sensores/raspberry/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Obtiene todos los sensores asociados a un Raspberry Pi",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Obtener sensores por Raspberry Pi",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del Raspberry Pi",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entities.SensorResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/sensores/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Obtiene un sensor por su ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Obtener un sensor",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del sensor",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entities.SensorResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Actualiza un sensor existente",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Actualizar un sensor",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del sensor",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Sensor a actualizar",
                        "name": "sensor",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entities.UpdateSensorRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entities.SensorResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Elimina un sensor existente",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Eliminar un sensor",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del sensor",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/sensores/{id}/estado": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Actualiza el estado de un sensor existente",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Actualizar el estado de un sensor",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del sensor",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Estado a actualizar",
                        "name": "estado",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entities.UpdateEstadoSensorRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/tipos-sensores": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Obtiene todos los tipos de sensores de la base de datos",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tipo Sensores"
                ],
                "summary": "Obtener todos los tipos de sensores",
                "responses": {
                    "200": {
                        "description": "Lista de tipos de sensores obtenida exitosamente",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entities.TipoSensorResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Crea un nuevo tipo de sensor en la base de datos",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tipo Sensores"
                ],
                "summary": "Crear un nuevo tipo de sensor",
                "parameters": [
                    {
                        "description": "Tipo de sensor a crear",
                        "name": "TipoSensor",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entities.CreateTipoSensorRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Tipo de sensor creado exitosamente",
                        "schema": {
                            "$ref": "#/definitions/entities.TipoSensorResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/tipos-sensores/nombre/{nombre}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Obtiene un tipo de sensor por su nombre de la base de datos",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tipo Sensores"
                ],
                "summary": "Obtener un tipo de sensor por su nombre",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Nombre del tipo de sensor",
                        "name": "nombre",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Tipo de sensor obtenido exitosamente",
                        "schema": {
                            "$ref": "#/definitions/entities.TipoSensorResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/tipos-sensores/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Obtiene un tipo de sensor por su ID de la base de datos",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tipo Sensores"
                ],
                "summary": "Obtener un tipo de sensor por su ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del tipo de sensor",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Tipo de sensor obtenido exitosamente",
                        "schema": {
                            "$ref": "#/definitions/entities.TipoSensorResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Actualiza un tipo de sensor existente en la base de datos",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tipo Sensores"
                ],
                "summary": "Actualizar un tipo de sensor existente",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del tipo de sensor",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Tipo de sensor a actualizar",
                        "name": "TipoSensor",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entities.UpdateTipoSensorRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Tipo de sensor actualizado exitosamente",
                        "schema": {
                            "$ref": "#/definitions/entities.TipoSensorResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Elimina un tipo de sensor existente de la base de datos",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tipo Sensores"
                ],
                "summary": "Eliminar un tipo de sensor existente",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del tipo de sensor",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Tipo de sensor eliminado exitosamente",
                        "schema": {
                            "$ref": "#/definitions/entities.TipoSensorResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "entities.CalibracionResponse": {
            "type": "object",
            "properties": {
                "factor_calibracion": {
                    "type": "number",
                    "example": 1.5
                },
                "fecha_calibracion": {
                    "type": "string",
                    "example": "2024-03-20T10:00:00Z"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "id_colmena": {
                    "type": "integer",
                    "example": 1
                },
                "id_sensor": {
                    "type": "integer",
                    "example": 1
                },
                "offset_calibracion": {
                    "type": "number",
                    "example": 0.5
                },
                "valor_maximo": {
                    "type": "number",
                    "example": 30.5
                },
                "valor_minimo": {
                    "type": "number",
                    "example": 20.5
                }
            }
        },
        "entities.ColmenaRaspberryResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2024-03-20T10:00:00Z"
                },
                "estado": {
                    "type": "string",
                    "example": "activo"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "id_colmena": {
                    "type": "integer",
                    "example": 1
                },
                "id_raspberry": {
                    "type": "integer",
                    "example": 1
                },
                "updated_at": {
                    "type": "string",
                    "example": "2024-03-20T10:00:00Z"
                }
            }
        },
        "entities.ColmenaResponse": {
            "type": "object",
            "properties": {
                "area_ubicacion": {
                    "type": "string",
                    "example": "Sector Norte"
                },
                "estado": {
                    "type": "string",
                    "example": "activo"
                },
                "fecha_actualizacion": {
                    "type": "string",
                    "example": "2024-03-20 10:00:00"
                },
                "fecha_registro": {
                    "type": "string",
                    "example": "2024-03-20 10:00:00"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "identificador": {
                    "type": "string",
                    "example": "COL-001"
                },
                "nombre": {
                    "type": "string",
                    "example": "Colmena Principal"
                },
                "tipo_colmena": {
                    "type": "string",
                    "example": "Langstroth"
                }
            }
        },
        "entities.ColmenasListResponse": {
            "type": "object",
            "properties": {
                "colmenas": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entities.ColmenaResponse"
                    }
                }
            }
        },
        "entities.CreateCalibracionRequest": {
            "type": "object",
            "properties": {
                "factor_calibracion": {
                    "type": "number",
                    "example": 1.5
                },
                "fecha_calibracion": {
                    "type": "string",
                    "example": "2024-03-20T10:00:00Z"
                },
                "id_colmena": {
                    "type": "integer",
                    "example": 1
                },
                "id_sensor": {
                    "type": "integer",
                    "example": 1
                },
                "offset_calibracion": {
                    "type": "number",
                    "example": 0.5
                },
                "valor_maximo": {
                    "type": "number",
                    "example": 30.5
                },
                "valor_minimo": {
                    "type": "number",
                    "example": 20.5
                }
            }
        },
        "entities.CreateColmenaRaspberryRequest": {
            "type": "object",
            "required": [
                "estado"
            ],
            "properties": {
                "estado": {
                    "type": "string",
                    "enum": [
                        "activo",
                        "inactivo"
                    ],
                    "example": "activo"
                },
                "id_colmena": {
                    "type": "integer",
                    "example": 1
                },
                "id_raspberry": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "entities.CreateColmenaRequest": {
            "type": "object",
            "properties": {
                "area_ubicacion": {
                    "type": "string",
                    "example": "Sector Norte"
                },
                "estado": {
                    "type": "string",
                    "example": "activo"
                },
                "identificador": {
                    "type": "string",
                    "example": "COL-001"
                },
                "nombre": {
                    "type": "string",
                    "example": "Colmena Principal"
                },
                "tipo_colmena": {
                    "type": "string",
                    "example": "Langstroth"
                }
            }
        },
        "entities.CreateRaspberryPiRequest": {
            "type": "object",
            "required": [
                "estado",
                "ip_address",
                "mac",
                "modelo",
                "nombre"
            ],
            "properties": {
                "estado": {
                    "type": "string",
                    "enum": [
                        "activo",
                        "inactivo"
                    ],
                    "example": "activo"
                },
                "ip_address": {
                    "type": "string",
                    "example": "192.168.1.100"
                },
                "mac": {
                    "type": "string",
                    "example": "00:11:22:33:44:55"
                },
                "modelo": {
                    "type": "string",
                    "example": "Raspberry Pi 4B"
                },
                "nombre": {
                    "type": "string",
                    "example": "Raspberry-001"
                }
            }
        },
        "entities.CreateSensorRequest": {
            "type": "object",
            "required": [
                "estado"
            ],
            "properties": {
                "direccion_i2c": {
                    "type": "string",
                    "example": "1"
                },
                "estado": {
                    "type": "string",
                    "enum": [
                        "activo",
                        "inactivo"
                    ],
                    "example": "activo"
                },
                "fecha_registro": {
                    "type": "string",
                    "example": "2024-03-20 10:00:00"
                },
                "id_raspberry": {
                    "type": "integer",
                    "example": 1
                },
                "id_tipo_sensor": {
                    "type": "integer",
                    "example": 1
                },
                "pin_conexion": {
                    "type": "string",
                    "example": "1"
                }
            }
        },
        "entities.CreateTipoSensorRequest": {
            "type": "object",
            "properties": {
                "descripcion": {
                    "type": "string",
                    "example": "Sensor de temperatura DS18B20"
                },
                "nombre": {
                    "type": "string",
                    "example": "DS18B20"
                },
                "tipo_dato": {
                    "type": "string",
                    "example": "decimal"
                },
                "unidad_medida": {
                    "type": "string",
                    "example": "°C"
                }
            }
        },
        "entities.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "description": "Mensaje de error",
                    "type": "string",
                    "example": "Credenciales inválidas. Por favor, verifique su usuario y contraseña"
                }
            }
        },
        "entities.RaspberryPiListResponse": {
            "type": "object",
            "properties": {
                "raspberry_pis": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entities.RaspberryPiResponse"
                    }
                }
            }
        },
        "entities.RaspberryPiResponse": {
            "type": "object",
            "properties": {
                "estado": {
                    "type": "string",
                    "example": "activo"
                },
                "fecha_registro": {
                    "type": "string",
                    "example": "2024-03-20 10:00:00"
                },
                "fecha_ultima_conexion": {
                    "type": "string",
                    "example": "2024-03-20 10:00:00"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "ip_address": {
                    "type": "string",
                    "example": "192.168.1.100"
                },
                "mac": {
                    "type": "string",
                    "example": "00:11:22:33:44:55"
                },
                "modelo": {
                    "type": "string",
                    "example": "Raspberry Pi 4B"
                },
                "nombre": {
                    "type": "string",
                    "example": "Raspberry-001"
                }
            }
        },
        "entities.SensorResponse": {
            "type": "object",
            "properties": {
                "direccion_i2c": {
                    "type": "string",
                    "example": "1"
                },
                "estado": {
                    "type": "string",
                    "example": "activo"
                },
                "fecha_registro": {
                    "type": "string",
                    "example": "2024-03-20 10:00:00"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "id_raspberry": {
                    "type": "integer",
                    "example": 1
                },
                "id_tipo_sensor": {
                    "type": "integer",
                    "example": 1
                },
                "pin_conexion": {
                    "type": "string",
                    "example": "1"
                }
            }
        },
        "entities.TipoSensorResponse": {
            "type": "object",
            "properties": {
                "descripcion": {
                    "type": "string",
                    "example": "Sensor de temperatura DS18B20"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "nombre": {
                    "type": "string",
                    "example": "DS18B20"
                },
                "tipo_dato": {
                    "type": "string",
                    "example": "decimal"
                },
                "unidad_medida": {
                    "type": "string",
                    "example": "°C"
                }
            }
        },
        "entities.UpdateCalibracionRequest": {
            "type": "object",
            "properties": {
                "factor_calibracion": {
                    "type": "number",
                    "example": 1.5
                },
                "fecha_calibracion": {
                    "type": "string",
                    "example": "2024-03-20T10:00:00Z"
                },
                "id_colmena": {
                    "type": "integer",
                    "example": 1
                },
                "id_sensor": {
                    "type": "integer",
                    "example": 1
                },
                "offset_calibracion": {
                    "type": "number",
                    "example": 0.5
                },
                "valor_maximo": {
                    "type": "number",
                    "example": 30.5
                },
                "valor_minimo": {
                    "type": "number",
                    "example": 20.5
                }
            }
        },
        "entities.UpdateColmenaRaspberryRequest": {
            "type": "object",
            "required": [
                "estado"
            ],
            "properties": {
                "estado": {
                    "type": "string",
                    "enum": [
                        "activo",
                        "inactivo"
                    ],
                    "example": "activo"
                },
                "id_colmena": {
                    "type": "integer",
                    "example": 1
                },
                "id_raspberry": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "entities.UpdateColmenaRequest": {
            "type": "object",
            "properties": {
                "area_ubicacion": {
                    "type": "string",
                    "example": "Sector Norte"
                },
                "estado": {
                    "type": "string",
                    "example": "activo"
                },
                "identificador": {
                    "type": "string",
                    "example": "COL-001"
                },
                "nombre": {
                    "type": "string",
                    "example": "Colmena Principal"
                },
                "tipo_colmena": {
                    "type": "string",
                    "example": "Langstroth"
                }
            }
        },
        "entities.UpdateEstadoColmenaRequest": {
            "type": "object",
            "required": [
                "estado"
            ],
            "properties": {
                "estado": {
                    "type": "string",
                    "enum": [
                        "activo",
                        "inactivo"
                    ],
                    "example": "inactivo"
                }
            }
        },
        "entities.UpdateEstadoRaspberryPiRequest": {
            "type": "object",
            "required": [
                "estado"
            ],
            "properties": {
                "estado": {
                    "type": "string",
                    "enum": [
                        "activo",
                        "inactivo"
                    ],
                    "example": "inactivo"
                }
            }
        },
        "entities.UpdateEstadoSensorRequest": {
            "type": "object",
            "required": [
                "estado"
            ],
            "properties": {
                "estado": {
                    "type": "string",
                    "enum": [
                        "activo",
                        "inactivo"
                    ],
                    "example": "inactivo"
                }
            }
        },
        "entities.UpdateRaspberryPiRequest": {
            "type": "object",
            "required": [
                "estado",
                "modelo"
            ],
            "properties": {
                "estado": {
                    "type": "string",
                    "enum": [
                        "activo",
                        "inactivo"
                    ],
                    "example": "activo"
                },
                "ip_address": {
                    "type": "string",
                    "example": "192.168.1.100"
                },
                "macj": {
                    "type": "string",
                    "example": "00:11:22:33:44:55"
                },
                "modelo": {
                    "type": "string",
                    "example": "Raspberry Pi 4B"
                },
                "nombre": {
                    "type": "string",
                    "example": "Raspberry-001"
                }
            }
        },
        "entities.UpdateSensorRequest": {
            "type": "object",
            "required": [
                "estado"
            ],
            "properties": {
                "direccion_i2c": {
                    "type": "string",
                    "example": "1"
                },
                "estado": {
                    "type": "string",
                    "enum": [
                        "activo",
                        "inactivo"
                    ],
                    "example": "activo"
                },
                "id_raspberry": {
                    "type": "integer",
                    "example": 1
                },
                "id_tipo_sensor": {
                    "type": "integer",
                    "example": 1
                },
                "pin_conexion": {
                    "type": "string",
                    "example": "1"
                }
            }
        },
        "entities.UpdateTipoSensorRequest": {
            "type": "object",
            "properties": {
                "descripcion": {
                    "type": "string",
                    "example": "Sensor de temperatura DS18B20"
                },
                "nombre": {
                    "type": "string",
                    "example": "DS18B20"
                },
                "tipo_dato": {
                    "type": "string",
                    "example": "decimal"
                },
                "unidad_medida": {
                    "type": "string",
                    "example": "°C"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "description": "Introduce el token Bearer. Ejemplo: \"Bearer {token}\"",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    },
    "externalDocs": {
        "description": "Autenticación API",
        "url": "http://localhost:8081/swagger/index.html"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{"http"},
	Title:            "API de Sensores para Colmenas",
	Description:      "API para la gestión de sensores en colmenas",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
